build site:
  image: node:latest
  stage: build
  script:
    - cd GotchaFrontEnd
    - npm install --progress=false

lint:
  image: node:latest
  stage: test
  script:
    - cd GotchaFrontEnd
    - npm install --progress=false
    - npm run lint

unit test:
  image: node:latest
  stage: test
  script:
    - cd GotchaFrontEnd
    - npm install --progress=false
    - npm run test:unit 
